### ISSUE TITLE
NodeJS Code Examples are out of date and don't work

### ISSUE THREAD

**Issue by alisalama** [cryptohopper/code-samples#1]
NodeJS Code Examples are out of date and don't work.

simple-oauth2 moved from version 3 to 4 and introduced breaking changes.

**Comment by fabiobozzo** [comment]
Hi @alisalama . Our team is working to improve the node.js examples. 🙂 
They will be based on simple-oauth2 **v4**, indeed (which is only compatible with Node.js > 12) ⚠️

**Comment by alisalama** [comment]
Thanks Fabio. Sounds great.

I ended up building my own but took me a while to figure out all the pieces of the OAuth, so a quickstarter as you've done in your pull request is great!

**Comment by fabiobozzo** [comment]
@alisalama glad you found the new js code helpful. I just merged the PR so that it's generally available.
